### ISSUE TITLE
Need to update structure

### ISSUE THREAD

**Issue by claywd** [Leszek111/ReLaunchX#12]
On importing your project to android studio it can't resolve :libs:ebookparser in build.gradle

**Comment by Leszek111** [comment]
Did you clone the submodule? There is no .iml file in the submodule but that one Android Studio should auto generate.

Regarding submodules:
Easiest way is to do _git clone --recursive repo.git_ You can also utilize the _git submodule_  command set.

**Comment by matthewjt** [comment]
I was able to get this working in the android studio.  Start a new project and import from git.  After you hit the Clone button it'll ask you if you want to make a new project for the repo.  Do NOT hit Yes to that yet.  Open you command line and go to the base folder you just cloned the repo into.  Run the command:
git submodule update --init --recursive
This will clone the ebookparser module.  You should be good to go then.

**Comment by Leszek111** [comment]
Hi @matthewjt, thanks for your feedback now I know where the problem comes from. Unfortunately the "import from Github" startup wizard in AndroidStudio does not have any option to clone the repo with submodules. 

The best approach is to clone the repo using git from command line, using Git Desktop, etc., with submodules then launch AndroidStudio and open the project from disk.

Command line approach:
`git clone --recursive https://github.com/Leszek111/ReLaunchX.git`
or
`git clone https://github.com/Leszek111/ReLaunchX.git`
`git submodule update --init`
